version: '3.8'

services:
  dashboard:
    container_name: modern-dashboard
    build: .
    restart: unless-stopped
    ports:
      - "3005:80"
    volumes:
      - ./public/config.json:/usr/share/nginx/html/config.json:ro
    networks:
      - dashboard-net

networks:
  dashboard-net:
    driver: bridge
