version: '3.8'

services:
  sboard:
    container_name: sboard
    build: .
    restart: unless-stopped
    ports:
      - "3005:5858"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./stacks:/app/stacks
      - ./data:/app/data
      - /:/.host:ro
    environment:
      - HOST_PROJECT_PATH=/home/mebs/pi-hosted/sboard
    networks:
      - dashboard-net

networks:
  dashboard-net:
    driver: bridge
